# This file was generated by liblab | https://liblab.com/

from booking import Booking, Environment
from booking.models import SearchInputDto, SearchAccept

sdk = Booking(
    access_token="YOUR_ACCESS_TOKEN",
    api_key="YOUR_API_KEY",
    api_key_header="YOUR_API_KEY_HEADER",
    base_url=Environment.DEFAULT.value,
)

request_body = SearchInputDto(
    checkin="checkin",
    checkout="checkout",
    booker={
        "country": "xb",
        "platform": "ANDROID",
        "travel_purpose": "BUSINESS",
        "user_groups": ["AUTHENTICATED"],
    },
    currency="EUR",
    city=1,
    country="nl",
    guests={
        "number_of_adults": 10,
        "number_of_rooms": 10,
        "allocation": [{"children": [8], "number_of_adults": 4}],
        "children": [14],
    },
    extras=["EXTRA_CHARGES"],
    accommodations=[7],
    accommodation_facilities=[0],
    room_facilities=[1],
    accommodation_types=[2],
    brands=[5],
    airport="AMS",
    district=2,
    landmark=10,
    coordinates={"latitude": 5.31, "longitude": 2.65, "radius": 8.29},
    region=0,
    rows=845,
    page="page",
)

result = sdk.demand_api_v3_compatible.search(
    request_body=request_body, accept="application/json"
)

print(result)
